### ISSUE TITLE
Segmentation fault while opening Hex Editor

### ISSUE THREAD

**Issue by Aleryc** [GuidoBartoli/sherloq#19] opened 2020-07-16 20:54 UTC
**Environment**

Ubuntu 18.04.4 LTS
Python 3.7.6

**uname output**
```
uname -a
Linux aleryc-pc 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Installed Packages (venv)**
```
absl-py==0.9.0
astor==0.8.1
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
concurrent-iterator==0.2.6
cycler==0.10.0
decorator==4.4.2
gast==0.3.3
google-auth==1.19.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
idna==2.10
imageio==2.9.0
importlib-metadata==1.7.0
joblib==0.16.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lxml==4.5.2
Markdown==3.2.2
matplotlib==3.2.2
networkx==2.4
numpy==1.19.0
oauthlib==3.1.0
opencv-contrib-python-headless==4.3.0.36
opt-einsum==3.2.1
pandas==1.0.5
Pillow==7.2.0
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
PySide2==5.15.0
python-dateutil==2.8.1
python-magic==0.4.18
pytz==2020.1
PyWavelets==1.1.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scikit-learn==0.23.1
scipy==1.5.1
sewar==0.4.3
shiboken2==5.15.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
threadpoolctl==2.1.0
tifffile==2020.7.4
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1
xgboost==1.1.1
zipp==3.1.0
```

**Console Output**
```
WARNING:tensorflow:From /home/aleryc/.virtualenvs/sq/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[1]    25858 segmentation fault (core dumped)  python3 sherloq.py
```

**Step to reproduce issue**
1. Load Image (I only tried with PNG and JPEG).
2. Double click on **Hex Editor** in **TOOLS** tab

Thank you

**Comment by GuidoBartoli** [comment] 2020-07-19 21:19
Hi,
I'm really sorry, but I cannot reproduce your error here:
![Peek 2020-07-19 23-13](https://user-images.githubusercontent.com/16103676/87885386-ca935a80-ca15-11ea-86c3-8c80b32eab2f.gif)

Please note that at the moment the *Hex Editor* is a simple wrapper for the online tool [HexEd.it](https://hexed.it/), so one opened you have to manually load the image file inside of it to display the content.

However these are the package installed in the virtual environment and actually some are different from yours:
```
absl-py==0.9.0
astor==0.8.1
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
concurrent-iterator==0.2.6
cycler==0.10.0
decorator==4.4.2
gast==0.3.3
google-auth==1.19.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
idna==2.10
imageio==2.9.0
joblib==0.16.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lxml==4.5.2
Markdown==3.2.2
matplotlib==3.3.0
networkx==2.4
numpy==1.19.0
oauthlib==3.1.0
opencv-contrib-python-headless==4.3.0.36
opt-einsum==3.2.1
pandas==1.0.5
Pillow==7.2.0
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
PySide2==5.15.0
python-dateutil==2.8.1
python-magic==0.4.18
pytz==2020.1
PyWavelets==1.1.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scikit-learn==0.23.1
scipy==1.4.1
sewar==0.4.3
shiboken2==5.15.0
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
threadpoolctl==2.1.0
tifffile==2020.7.17
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1
xgboost==1.1.1
```

Did you follow the latest instructions in the [README](https://github.com/GuidoBartoli/sherloq/blob/master/README.md#linux)?

**Comment by GuidoBartoli** [comment] 2020-12-21 07:01
No additional info received and unable to reproduce, closing this issue.

**Closed by GuidoBartoli** 2020-12-21 07:01 UTC
Labels: missing info
