### ISSUE TITLE
stress test cloning.py

### ISSUE THREAD

**Issue by under-score** [GuidoBartoli/sherloq#20] opened 2020-07-21 15:38 UTC
when testing now a large number of files on the command line, I could identify a bmp and a jpg file that run forever
[Archiv.zip](https://github.com/GuidoBartoli/sherloq/files/4954448/Archiv.zip)

**Comment by GuidoBartoli** [comment] 2020-07-21 20:14
Ok, thanks for providing source images, I will take a look at it tomorrow.

**Comment by GuidoBartoli** [comment] 2020-07-21 20:57
I could not read the BMP image, OpenCV seems unable to decode the contents:
```imread_('Im2.299x397.bmp'): can't read data: OpenCV(4.3.0) /io/opencv/modules/imgcodecs/src/bitstrm.cpp:110: error: (-2:Unspecified error) Unexpected end of input stream in function 'readBlock'```
How did you load it?

The second one causes BRISK to find a huge amount of keypoints (black symbols on white background are very _responsive_), so clustering can take a lifetime. If you lower the **Response** parameter, you filter out weaker keypoints and clustering can be feasible (i.e. below is the result with response = 20%):

![cmf](https://user-images.githubusercontent.com/16103676/88106271-8040e380-cba5-11ea-8eb1-e6e65907dfc5.png)

**Comment by under-score** [comment] 2020-07-22 07:48
No problem loading BMP images with Preview or Affinity Photo under MacOS. Could not find anything unusual in the exif data but no chance to open the BMPs with OpenCV or ImageMagick. Just for the records sips works as pre-processor
`sips -s format png image.bmp --out image.png`
Regarding too many keypoints: Would automatic lowering the response a solution? Would a plot number of keypoints versus response informative? So far, I just kill the script after 120 seconds...

**Comment by GuidoBartoli** [comment] 2020-07-23 07:33
Well actually there is no keypoint limit, but a warning could be easily added to Copy-Move Forgery (however note the computation time depends on the local CPU).
With the previous image, I simply canceled clustering and lowered Response until I get the result in a reasonable time (about 6 seconds on my PC).

**Comment by under-score** [comment] 2020-07-23 14:07
here is another image forgery
![EdgLBZCU0AA91qa](https://user-images.githubusercontent.com/2796454/88295813-34558200-ccfe-11ea-8c63-8c3d4517c0b8.png)
that isn't detected by BRISK - the horizontally mirrored square from lower right to upper right
![EdhHp8-XgAAYuac](https://user-images.githubusercontent.com/2796454/88296000-71217900-ccfe-11ea-879d-ab1e6a654438.png)

**Comment by GuidoBartoli** [comment] 2020-07-23 18:57
I had no problem in finding cloned regions with the following settings:
![cmf](https://user-images.githubusercontent.com/16103676/88326654-90cc9780-cd26-11ea-9e7d-5fa089f66c12.jpg)
But be aware that actually CMF cannot detect mirrored regions, it is something planned for a future version.

**Comment by under-score** [comment] 2020-07-24 06:32
good to know (thought that mirroring would be easier to detect than rotation)

**Comment by under-score** [comment] 2020-07-24 14:56
![Im0 0](https://user-images.githubusercontent.com/2796454/88404702-882f9c00-cdce-11ea-94e9-5c13635b3611.jpg)
another day another example
`strongest = (cv.normalize(responses, None, 0, 100, cv.NORM_MINMAX) >= response).flatten()`
produces
`TypeError: '>=' not supported between instances of 'NoneType' and 'int'`

**Comment by GuidoBartoli** [comment] 2020-07-24 23:09
Mmmh cannot reproduce this... it seems a previous bug fixed in 947d4265ddb34a57f73755a9d93ada5a6993e23f.
Can you please update to the latest version and try again?

**Comment by under-score** [comment] 2020-07-25 14:20
no more error ;-)

**Comment by under-score** [comment] 2020-07-27 05:33
this one is hardly recognized row3col2 is identical to row4col1
![Bildschirmfoto 2020-07-27 um 07 18 45](https://user-images.githubusercontent.com/2796454/88506743-ed57dd00-cfda-11ea-8cc4-1fcd52e167de.jpg)

while I have the general impression that slightly unsharp pictures are more difficult to be recognized as well as pictures treated with the liquify filter
![Bildschirmfoto 2020-07-27 um 07 28 18](https://user-images.githubusercontent.com/2796454/88506824-2728e380-cfdb-11ea-9fd1-f2b8f0e63fdc.jpg)

**Comment by GuidoBartoli** [comment] 2020-07-27 06:09
In these cases you have to raise the Matching threshold to allow detection of weaker keypoints in blurred regions (I used 50% below and added a mask to ignore text areas):

![cmf](https://user-images.githubusercontent.com/16103676/88508961-52fa9800-cfe0-11ea-883a-4c68615bbadf.png)

**Closed** 2020-11-03 10:32 UTC
Labels: question
