### ISSUE TITLE
Huge variance in Eigenvalues for seemingly similar images

### ISSUE THREAD

**Issue by Ray9T** [GuidoBartoli/sherloq#90] opened 2024-06-20 19:39 UTC
@GuidoBartoli 
Wondering if something changed in the current version that is causing huge Eigenvalue variance among identical images, which was consistent in previous version (was a huge aid in quantitatively categorizing similar images).

Images in the test
Test image 1: https://www.imaging-resource.com/PRODS/sony-a99-ii/A99M2hSLI000050NR0.ARW.HTM
Test Image 2 : https://www.imaging-resource.com/PRODS/sony-a99-ii/A99M2hSLI000050NR2D.ARW.HTM

Both Test images are identical
![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/e89eec24-d8dc-4448-a0dd-497f0bb665bd)

0.89c version shows huge Eigenvalue **variance** for identical images
![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/9564da93-6a64-45e7-ab73-dd6a06c55b20)

Previous version was consistent across all channels for EigenValues
![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/79d0ad87-4cff-4810-a3bb-9d7cf659fbc0)

**Comment by atadams** [comment] 2024-06-20 22:19
I believe @Ray9T’s issue with the Eigenvalue variance is related to the issue I mentioned in Issue 86 (I opened a [new issue from that comment](https://github.com/GuidoBartoli/sherloq/issues/91)). It has to do with using the float32 data type in pca.py. It limits the sums of the pixels when calculating means. You'll notice in Ray9T's grabs that the Mean vectors are equal. The cause of this is described in detail in [issue 91](https://github.com/GuidoBartoli/sherloq/issues/91).

If you change `float32` to `float64` on line 40 of pca.py, the variance between the Eigenvalues of the two files appears normal, and the Mean vectors are no longer equal.

**PCA with float64**
<img width="1356" alt="float64-sherloq" src="https://github.com/GuidoBartoli/sherloq/assets/392510/6541b457-8b54-4ed2-bab0-967d660c29c3">

Making that change should resolve both @Ray9T and my issues.

Thank you for your work on this project. It's a great resource.

**Comment by Ray9T** [comment] 2024-06-20 22:22
I dont think that's the issue @atadams , there are multiple changes made in this version based on change log, and would prefer a more through response.

**Comment by Ray9T** [comment] 2024-06-21 00:56
@Ray9T atadams is trying to make his fake image problem **go away** at the expense of the app's integrity. His Raw images, which are used to spread disinformation is exactly what apps like Sherloq are designed to catch.

0.87c is still the best version that's still accurately flagging fake images, showing the noise anomalies where edits are made, and shows the expected PCA values for similar images. 

Here we have these guys manipulating the app to make their image problem disappear. Fortunately, there are apps like Darktable that are still flagging these atadams images.

**Comment by GuidoBartoli** [comment] 2024-06-21 12:23
> If you change `float32` to `float64` on line 40 of pca.py, the variance between the Eigenvalues of the two files appears normal, and the Mean vectors are no longer equal.

Fixed in d6a3b98e7fb88dc41bd3caa70d8160b20d330d48.

> I dont think that's the issue @atadams , there are multiple changes made in this version based on change log, and would prefer a more through response.

Commits from 8ecde4983cce45bfead58e26eb47e334dd8a89e6 to 3b638df5f7bf03deb737f1e992f422695ef7d4a2 include fixes for other issues, but the only change I made to cope with clipping issues during RAW import is the one suggested by @atadams.

**Closed by GuidoBartoli** 2024-06-21 12:23 UTC
